[dependencies.panic-rauk]
git = "https://github.com/markhakansson/panic-rauk.git"
version = "0.1"
optional = true

[dependencies.klee-rs]
git = "https://github.com/markhakansson/klee-rs.git"
version = "0.1"
optional = true

[dependencies.vcell]
version = "0.1.3"
optional = true

[patch.crates-io]
cortex-m = { git = "https://github.com/markhakansson/cortex-m.git", branch = "rauk-0.6.0-alpha.2" }
#cortex-m-rtic = { git = "https://github.com/markhakansson/cortex-m-rtic.git", branch = "rauk-0.6.0-alpha.2" }
cortex-m-rtic = { path = "../cortex-m-rtic" }
cortex-m-rt = { git = "https://github.com/markhakansson/cortex-m-rt.git", branch = "klee" }
vcell = { git = "https://github.com/markhakansson/vcell.git", branch = "klee" }

[features]
klee-analysis = [
    "panic-rauk",
    "klee-rs",
    "cortex-m/klee-analysis",
    "vcell/klee-analysis",
    "cortex-m-rtic/klee-analysis",
    "cortex-m-rt/klee-analysis",
]
klee-replay = [
    "cortex-m-rtic/klee-replay",
    "vcell/klee-replay",
]
